# Generated by Django 3.2.4 on 2021-11-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.IntegerField(choices=[(1, '颜色1'), (2, '颜色2'), (3, '颜色3'), (4, '颜色4')])),
                ('size', models.IntegerField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA LARGE'), ('2XL', '2 EXTRA LARGE'), ('3XL', '3 EXTRA LARGE'), ('4XL', '4 EXTRA LARGE'), ('5XL', '5 EXTRA LARGE')])),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
