# Generated by Django 3.2.4 on 2021-11-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA LARGE'), ('2XL', '2 EXTRA LARGE'), ('3XL', '3 EXTRA LARGE'), ('4XL', '4 EXTRA LARGE'), ('5XL', '5 EXTRA LARGE')], max_length=3),
        ),
    ]
