# Generated by Django 3.2.4 on 2021-11-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
